config/urls.py
from django.contrib import admin
from django.urls import path, include
<<<<<<< HEAD
from pybo.views import base_view

urlpatterns = [
    path("", base_view.index, name='index'),
    path("admin/", admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls'))
=======
from pybo import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('pybo/',include('pybo.urls')),
>>>>>>> f0cf70c187a02ef13c7821c4c612dbff267fc274
]

pybo/urls.py
from django.urls import path
<<<<<<< HEAD
from .views import base_view, question_views, answer_view, comment_view, vote_views
=======
from . import views
>>>>>>> f0cf70c187a02ef13c7821c4c612dbff267fc274

app_name = 'pybo'

urlpatterns = [
<<<<<<< HEAD
    path('', base_view.index, name='index'),                      # 목록 보기
    path('<int:question_id>/', base_view.detail, name='detail'),   # 상세 보기
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    path('answer/create/<int:question_id>/', answer_view.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_view.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_view.answer_delete, name='answer_delete'),

    path('comment/create/question/<int:question_id>/', comment_view.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_view.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_view.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', comment_view.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_view.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_view.comment_delete_answer, name='comment_delete_answer'),

    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

=======
    path('', views.index, name='index'),                    # 목록보기
    path('<int:question_id>/', views.detail, name='detail'), # 상세 보기   <변환함수:변수명>, 
    path('answer/create/<int:question_id>/', views.answer_create,
        name='answer_create')
]
>>>>>>> f0cf70c187a02ef13c7821c4c612dbff267fc274

pybo/models.py
from django.db import models
<<<<<<< HEAD
from django.contrib.auth.models import User

class Question(models.Model):
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField('제목', max_length=200,
                               help_text='질문의 제목을 한 줄로 작성하세요.')
    content = models.TextField('내용', help_text='질문의 내용을 상세히 작성하세요.')
    create_date = models.DateTimeField('생성일')
    modify_date = models.DateTimeField(null=True, blank=True)

    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return f'{self.id} {self.subject}'


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='author_answer')    
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField('답변 내용')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    voter = models.ManyToManyField(User, related_name='voter_answer')
    
    def __str__(self):
        return self.content
    

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField('댓글 내용')
    create_date = models.DateTimeField('생성일')
    modify_date = models.DateTimeField('수정일', null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, 
                                 on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, 
                               on_delete=models.CASCADE)
    
    

    def __str__(self):
        return self.content
=======

# Create your models here.
class Question(models.Model):
    subject = models.CharField('제목', max_length=200)
    content = models.TextField('내용')
    create_date = models.DateTimeField('생성일')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content
>>>>>>> f0cf70c187a02ef13c7821c4c612dbff267fc274

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        widgets = {
            'subject': forms.TextInput(attrs={'placeholder': '제목을 입력하세요.'}),
            'content': forms.Textarea(attrs={'placeholder': '내용을 입력하세요.'}),
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . models import Question
from django.utils import timezone

# Create your views here.
def index(request):
    """ pybo 출력 """
    question_list=Question.objects.order_by('-create_date')
    context = {'question_list': question_list}

    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    # print(request.method)
    # print(request.GET) #dict
    # print(request.POST)#dict

    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'),
                create_date=timezone.now())

    return redirect('pybo:detail', question_id=question_id)
    

pybo/views/answer_view.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..models import Question, Answer
from ..forms import  AnswerForm


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            # 애커 #answer_7 추가
            url = resolve_url('pybo:detail', question_id=question.id)
            url += f'#answer_{answer.id}'
            return redirect(url)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)



@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            url = resolve_url('pybo:detail', question_id=answer.question.id)
            url +=f'#answer_{answer.id}'
            return redirect(url)
    else:
        form = AnswerForm(instance=answer)

    context = {'answer': answer, 'form': form}

    return render(request, 'pybo/answer_form.html', context)



@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_view.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Question

def index(request):
    """
    pybo 목록 출력
    """
    page = request.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
  
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_view.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..models import Question, Answer, Comment
from ..forms import CommentForm



@login_required(login_url='common:login')
def comment_create_question(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            url = resolve_url('pybo:detail', question_id=question.id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)
    else:
        form = CommentForm()
        
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문댓글 수정
    """
    comment=get_object_or_404(Comment,pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    if request.method == "POST":
        form=CommentForm(request.POST, instance=comment)
        if form.is_Valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            url = resolve_url('pybo:detail', question_id=comment.question.id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)
        
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)
       

@login_required(login_url='common:login')
def comment_delete_question(request,comment_id):
    """
    pybo 질문 댓글 삭제
    """
    comment=get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            url = resolve_url('pybo:detail', question_id=answer.question.id)
            url += f'#comment_{{comment.id}}'
            return redirect(url)

    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """ 
    pybo 답글 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            url = resolve_url('pybo:detail', question_id=comment.answer.question.id)
            url += f'#comment_{comment.id}'

            return redirect(url)
    
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Question
from ..forms import QuestionForm

@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
        

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)



@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        # 질문 수정을 위해 값 덮어쓰기
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        # 질문 수정 화면에 기존 제목, 내용 반영
        form = QuestionForm(instance=question)

    context = {'form': form}

    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from ..models import Question, Answer
@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    pybo 질문 추천 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답글 추천 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_create_form.html
<form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
  {% csrf_token %}
  {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
          <strong>{{ field.label }}</strong>
          {{ field.errors }}
        {% endif %}
      {% endfor %}
    </div>
  {% endif %}

  <div class="form-group">
    <textarea {% if not user.is_authenticated %} disabled="disabled" {% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
  </div>
  <input type="submit" value="답변등록" class="btn btn-primary">
</form>

templates/pybo/answer_list.html
{% load pybo_filter %}

<h5 class="border-bottom my-3 py-2">
  <i class="fa-solid fa-comments"></i>
  {{question.answer_set.count}}개의 답변이 있습니다.
</h5>

{% for answer in question.answer_set.all %}
  <a name="answer_{{answer.id}}"></a>
  <div class="row my-3">
    <div class="col-1">
      <!-- 추천 영역 -->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        {{ answer.voter.count }}
      </div>
      <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <!--답변영역-->
      <div class="card">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
          <div class="d-flex justify-content-end">
            {% if answer.modify_date %}
              <div class="badge badge-success p-2 mx-3 text-left">
                <div class="mb-2">수정일</div>
                <div>
                  <i class="fa-regular fa-clock"></i>
                  {{ answer.modify_date | date:'Y-m-d H:i' }}
                </div>
              </div>
            {% endif %}
            <div class="badge badge-success p-2 text-left">
              <div class="mb-2">
                <img class="avarta-sm" src="https://randomuser.me/api/portraits/men/{{answer.author.id}}.jpg"/>
                {{ answer.author.username }}
              </div>

              <div>
                <i class="fa-regular fa-clock"></i>
                {{ answer.create_date | date:'Y-m-d H:i' }}
              </div>
            </div>

          </div>

          {% if request.user == answer.author %}
            <div class="my-3">
              <a href="{% url 'pybo:answer_modify' answer.id  %}" class="btn btn-sm btn-outline-secondary">
                <i class="fa-solid fa-pen-to-square mr-2"></i>
                수정</a>

              <a href="#" class="delete btn btn-sm btn-outline-secondary text-danger" data-uri="{% url 'pybo:answer_delete' answer.id  %}">
                <i class="fa-regular fa-trash-can"></i>
                삭제</a>
            </div>
          {% endif %}

          <!-- 답변에 대한 댓글 -->
          {% include 'pybo/comment_answer.html' %}

        </div>
      </div>
    </div>
  </div>

{% endfor %}

templates/pybo/comment_answer.html
{% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="card body">
      {% if answer.comment_set.count > 0 %}
        <a name="comment_{{comment.id}}"></a>
        <div class="mt-3">
          {% for comment in answer.content_set.all %}
            <div class="comment py-2 text-muted">
              <span style="white-space: pre-line;">
                {{ comment.content }}
              </span>
              <span>
                -
                {{ comment.author }},
                {{ comment.create_date }}
                {% if comment.modify_date %}
                  (수정:{{ comment.modify_date }})
                {% endif %}
              </span>
              {% if request.user == comment.author %}
                <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="samll">수정</a>
                <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
              {% endif %}
            </div>
          {% endfor %}
        </div>
      {% endif %}
      <div>
        <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="samll">
          <small>댓글 추가 ..</small>
        </a>
      </div>
    </div>
  </div>
{% endfor %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="container my-3">
    <h5 class="border-bottom pb-2">
      <i class="fa-regular fa-comment"></i>
      댓글 등록하기</h5>
    <form method="post" class="post-form my-3">
      {% csrf_token %}

      {% bootstrap_form form %}

      <button type="submit" class="btn btn-primary">
        <i class="fa-solid fa-check"></i>
        저장하기</button>
    </form>
  </div>
{% endblock %}

templates/pybo/comment_question.html
<!-- 질문 댓글 -->
{% if question.comment_set.count > 0 %}
  <div class="mt-3 p-3">

    {% for comment in question.comment_set.all %}
      <a name="comment_{{comment.id}}"></a>
      <div class="comment py-2 text-muted">
        <span style="white-space: pre-line;">{{ comment.content }}</span>
        <span class="ml-3">
          -
          <img class="avarta-sm" src="https://randomuser.me/api/portraits/men/{{comment.author.id}}.jpg"/>
          {{ comment.author }},
          {{ comment.create_date | date:'Y-m-d H:i'}}
          {% if comment.modify_date %}
            (수정:{{ comment.modify_date  | date:'Y-m-d H:i'}})
          {% endif %}
        </span>

        {% if request.user == comment.author %}
          <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">
            <i class="fa-solid fa-pen-to-square ml-2"></i>
            수정</a>,
          <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">
            <i class="fa-regular fa-trash-can"></i>
            삭제</a>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endif %}
<div class="ml-3">
  <a href="{% url 'pybo:comment_create_question' question.id %}" class="small">
    <small>
      <i class="fa-regular fa-square-plus"></i>
      댓글 추가 ..</small>
  </a>
</div>
<!-- 질문 댓글 End -->

templates/pybo/question_detail.html
<<<<<<< HEAD
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
  <!-- 사용자오류 표시 -->
  {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
      {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
          <li>{{ message.message }}</li>
        </ul>
      {% endfor %}
    </div>
  {% endif %}

  <h2 class="border-bottom py-2">
    <i class="fa-solid fa-clipboard-question"></i>
    {{ question.subject }}
  </h2>

  <div class="row my-3">
    <div class="col-1">
      <!-- 추천 영역 -->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        {{question.voter.count}}
      </div>
      <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class='col-11'>
      <!-- 질문 영역 -->

      <div class="card">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">{{ question.content|mark }}</div>
          <div class="d-flex justify-content-end">
            {% if question.modify_date %}
              <div class="badge badge-success p-2 mx-3 text-left">
                <div class="mb-2">수정일</div>
                <div>
                  <i class="fa-regular fa-clock"></i>
                  {{ question.modify_date | date:'Y-m-d H:i' }}
                </div>
              </div>
              {%endif%}
              <div class="badge badge-primary p-2 text-left">
                <div class="mb-2">
                  <img class="avarta-sm" src="https://randomuser.me/api/portraits/men/{{question.author.id}}.jpg"/>
                  {{ question.author.username }}</div>
                <div>
                  <i class="fa-regular fa-clock"></i>
                  {{ question.create_date | date:'Y-m-d H:i' }}
                </div>
              </div>
            </div>

            {% if request.user == question.author %}
              <div class="my-3">
                <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">
                  <i class="fa-solid fa-pen-to-square mr-2"></i>
                  수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary text-danger" data-uri="{% url 'pybo:question_delete' question.id  %}">
                  <i class="fa-regular fa-trash-can"></i>
                  삭제</a>
              </div>
            {% endif %}
          </div>

          {% include 'pybo/comment_question.html' %}

        </div>
      </div>
    </div>

    {% include 'pybo/answer_list.html' %}

    {% include 'pybo/answer_create_form.html' %}

    <a href="{% url 'pybo:index' %}">목록보기</a>
  {% endblock content %}

  {% block script %}
    <script>
      $(document).ready(function () {
        console.log('로딩 완료');
        let btns = $('.delete'); // 변수 선언 키워드 let
        btns.on('click', function () {
          console.log('click 발생');
          let answer = confirm('정말 삭제할까요?');
          if (answer) {
            location.href = $(this).data('uri');
          }
        });

        $('.recommend').on('click', function () {
          if (confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
          }
        });
        console.log('click 이벤트 핸들러 등록 완료');
      });
    </script>
  {% endblock script %}
=======
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>

<h1>{{ question.subject }}</h1>

<div>
  {{ question.content }}
</div>
<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
  <ul>
    {% for answer in question.answer_set.all %}
      <li>{{ answer.content }}</li>
    {% endfor %}
  </ul>
</div>
<form action="{% url 'pybo:answer_create' question.id %}" method="POST">
  {% csrf_token %}
  <textarea name="content" id="content" rows="15"></textarea>
  <input type="submit" value="답변등록">

</form>

<a href="{% url 'pybo:index' %}">목록 보기</a>
>>>>>>> f0cf70c187a02ef13c7821c4c612dbff267fc274

templates/pybo/question_list.html
<<<<<<< HEAD
{% extends 'base.html' %}

{% block content %}
  <table class="table table-striped table-hover">
    <tr class="thead-dark">
      <th style="width:70px">번호</th>
      <th>추천</th>
      <th>제목</th>
      <th style="width:120px">글쓴이</th>
      <th style="width:160px">작성일시</th>
    </tr>
  </thead>
  <tbody>
    {% if question_list %}
      {% for question in question_list %}
        <tr>
          <td>{{ question.id }}</td>
          <td>
            {% if question.voter.all.count > 0 %}
              <span class="badge badge-warning px-2 py-1">
                {{ question.voter.all.count }}
              </span>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'pybo:detail' question.id %}">
              {{ question.subject }}
              {% if question.answer_set.count %}
                <span class="ml-2">
                  <i class="fa-regular fa-comment-dots"></i>
                  <sub>{{question.answer_set.count}}</sub>
                </span>
              {% endif %}
            </a>
          </td>
          <td>{{ question.author.username }}</td>
          <td>{{ question.create_date | date:'Y-m-d H:i'}}</td>

        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
    {% endif %}
  </tbody>
</table>

{% include 'pybo/pagination.html' %}

<a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
  <i class="fa-solid fa-pen-to-square mr-2"></i>
  질문 등록하기
</a>

{% endblock content %}>
=======
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"/>

<div class="container my-3">

  <table class="table table-hover">
    <thead>
      <tr class="thead-dark">
        <th>번호</th>
        <th>제목</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %}
        {% for question in question_list %}

          <tr>
            <td>{{ forloop.counter }}</td>
            <td>
              <a href="{% url 'pybo:detail' question.id %}">
                {{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
          </tr>
        {% endfor %}

      {% else %}
        <tr>
          <td colsapn="3">질문이 없습니다.</td>
        {% endif %}
      </tbody>
    </table>
  </div>
  {% if a %}{% endif %}
>>>>>>> f0cf70c187a02ef13c7821c4c612dbff267fc274